### ISSUE TITLE
Do you have an example capture file?

### ISSUE THREAD

**Issue by hadrielk** [hossimo/CITP-Dissector#5]
Hi,
I'd like to add your Lua plugin script to Wireshark's repository (I'm one of the developers).
Do you have an example packet capture of CITP traffic  to use with the script, that you would be willing to have publicly viewable?
Thanks,
-hadriel

**Comment by hossimo** [comment]
Sorry for the delay, apparently I'm not getting notifications.

If you still need it I have added an example in the [repo]( https://github.com/hossimo/CITP-Dissector/raw/master/Example%20Capture.pcapng)
